---
abstract: 'perl interface for libcaca (Colour AsCii Art library)'
author:
  - 'John Beppu <beppu@cpan.org>'
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-Caca
provides:
  Term::Caca:
    file: lib/Term/Caca.pm
    version: 2.0_0
  Term::Caca::Bitmap:
    file: lib/Term/Caca/Bitmap.pm
    version: 2.0_0
  Term::Caca::Constants:
    file: lib/Term/Caca/Constants.pm
    version: 2.0_0
  Term::Caca::Event:
    file: lib/Term/Caca/Event.pm
    version: 2.0_0
  Term::Caca::Event::Key:
    file: lib/Term/Caca/Event/Key.pm
    version: 2.0_0
  Term::Caca::Event::Key::Press:
    file: lib/Term/Caca/Event/Key/Press.pm
    version: 2.0_0
  Term::Caca::Event::Key::Release:
    file: lib/Term/Caca/Event/Key/Release.pm
    version: 2.0_0
  Term::Caca::Event::Mouse::Button:
    file: lib/Term/Caca/Event/Mouse/Button.pm
    version: 2.0_0
  Term::Caca::Event::Mouse::Button::Press:
    file: lib/Term/Caca/Event/Mouse/Button/Press.pm
    version: 2.0_0
  Term::Caca::Event::Mouse::Button::Release:
    file: lib/Term/Caca/Event/Mouse/Button/Release.pm
    version: 2.0_0
  Term::Caca::Event::Mouse::Motion:
    file: lib/Term/Caca/Event/Mouse/Motion.pm
    version: 2.0_0
  Term::Caca::Event::Quit:
    file: lib/Term/Caca/Event/Quit.pm
    version: 2.0_0
  Term::Caca::Event::Resize:
    file: lib/Term/Caca/Event/Resize.pm
    version: 2.0_0
  Term::Caca::Sprite:
    file: lib/Term/Caca/Sprite.pm
    version: 2.0_0
requires:
  Carp: 0
  Const::Fast: 0
  DynaLoader: 0
  Exporter: 0
  List::MoreUtils: 0
  Method::Signatures: 0
  base: 0
  constant: 0
  parent: 0
  perl: v5.10.0
  strict: 0
  vars: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Term-Caca
  homepage: http://search.cpan.org/dist/Term-Caca/
  repository: https://github.com/yanick/Term-Caca.git
version: 2.0_0
x_authority: cpan:YANICK
