---
abstract: 'perl interface for libcaca (Colour AsCii Art library)'
author:
  - 'John Beppu E<lt>beppu@cpan.orgE<gt>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-Caca
provides:
  Term::Caca:
    file: lib/Term/Caca.pm
    version: 0.96
  Term::Caca::Bitmap:
    file: lib/Term/Caca/Bitmap.pm
  Term::Caca::Constants:
    file: lib/Term/Caca/Constants.pm
    version: 0.9
  Term::Caca::Sprite:
    file: lib/Term/Caca/Sprite.pm
  Term::Kaka:
    file: lib/Term/Kaka.pm
  Term::Kaka::Bitmap:
    file: lib/Term/Kaka/Bitmap.pm
  Term::Kaka::Constants:
    file: lib/Term/Kaka/Constants.pm
  Term::Kaka::Sprite:
    file: lib/Term/Kaka/Sprite.pm
version: 0.96
